### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by hfrance** [JosephLai241/URS#17]
Hir sir, sorry about my english, I am french,

I have read the readme few time but i dont see this option.

Is it possible to post a comment on reddit post.

Thank you

**Comment by JosephLai241** [comment]
Hi @hfrance, no worries! I can understand what you are asking just fine.

Yes it is possible to [reply to a comment with PRAW](https://praw.readthedocs.io/en/latest/code_overview/models/comment.html#praw.models.Comment.reply), but I will not be adding this feature to URS.

I would like URS to remain strictly a scraper - a tool that *only* pulls data from Reddit; hence the name Universal Reddit *Scraper*. If I were to add functionality that allowed interaction beyond just scraping, URS will no longer just be a scraper. Instead it would become a general Reddit interaction tool, which is not in the project scope.
