### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by nilknarfamme** [JosephLai241/URS#25]
Hi, thanks so much for making this. It's really helpful.

I'm just wondering whether there is a way to also get the OP's comment text when scraping a submission using the 'Comments' function? At the moment I am only able to get the replies and not the original post for a specified URL.

Thanks a lot for any help or advice you can give!

**Comment by JosephLai241** [comment]
Hi @nilknarfamme, I actually just added this feature last night. If you go to the submission comments samples, you will see that there is a `"submission_metadata"` field within the `"data"` field near the top of the file. This block contains data pertaining to the original submission.

**Comment by nilknarfamme** [comment]
amazing, thank you!!
