### ISSUE TITLE
How do I grab posts from a subreddit from a specific month?

### ISSUE THREAD

**Issue by yudhiesh** [JosephLai241/URS#32]
Hi thanks for the great library! I am looking into scraping top posts within each month of this year or if that is not possible then scrap the top posts within a date range. How would I accomplish this?

**Comment by JosephLai241** [comment]
Unfortunately it is currently not possible to scrape top posts within each month of this year or the top posts within a date range. PRAW does not expose any endpoints offering such functionality as of v7.2.0.

I am looking into different ways to scrape Reddit, however, so features such as the ones you have described may be implemented in future iterations. Stay tuned for updates!

**Comment by yudhiesh** [comment]
@JosephLai241 sorry I forgot to post an update on this. I actually found a way using the [Pushshift API](https://github.com/pushshift/api). 

You can use the parameters `before` and `after` to specify the range but based on the current date. In the example I am taking the posts from 111 days before today. I suppose if you wanted to integrate it to your library the user would have to input the month or date range, then you calculate the range from the current date and then make a request. There is more info on the before and after parameters [here](https://github.com/pushshift/api#using-the-before-and-after-parameters).

```
import requests

before = 111, after = 112

link = f"https://api.pushshift.io/reddit/search/submission/?size=100&before={before}d&after={after}d&sort_type=num_comments&sort=desc&subreddit=wallstreetbets"
sample = requests.get(link)
```
