### ISSUE TITLE
Bug Report | Scrape data is not located within the `scrapes` directory when generating frequencies

### ISSUE THREAD

**Issue by lolfilmworks** [JosephLai241/URS#40]
# **DO NOT DELETE THIS TEMPLATE**

## Describe The Bug

I attempt to generate a Frequency json using the `-f` flag. I am able to generate scrapes perfectly fine, however any analytics return issues similar to the aforementioned directory issue.

## Expected Behavior

Frequency report generated.

## Actual Behavior

Received the ```Scrape data is not located within the `scrapes` directory.``` error.

## Steps To Reproduce

Ran the command: 

```
(venv) C:\Users\User\Desktop\URS-3.3.0\urs>python urs.py -f C:\Users\U\Desktop\URS-3.3.0\scrapes\06-22-2021\subreddits\Philosophy-hot--100-results.json
```

## Screenshots/Traceback

https://i.imgur.com/DhFDaHT.png

```
(venv) C:\Users\User\Desktop\URS-3.3.0\urs>python urs.py -f C:\Users\U\Desktop\URS-3.3.0\scrapes\06-22-2021\subreddit
s\Philosophy-hot--100-results.json

 __  __  _ __   ____  
/\ \/\ \/\`'__\/',__\ 
\ \ \_\ \ \ \//\__, `\
 \ \____/\ \_\\/\____/
  \/___/  \/_/ \/___/ 
  ___  
 /'___\ �
/\ \__/ 
\ \ ,__\ 
 \ \ \_/
  \ \_\
   \/_/
 __
/\_\
\/\ \
 \ \ \
  \ \_\
   \/_/... Scrape data is not located within the `scrapes` directory.
```

## Machine Specs

* Operating System: Windows 10 64 bit
* Python Version: ~~Python 3. 9. 5

## Additional Context

I am extremely new to coding and am sure I am missing something very simple.

**Comment by JosephLai241** [comment]
Your bug report is currently too vague. Please fill out the bug report template that I have created for this repository. For future reference, **do not delete the preset issue template when opening a new issue**.

You can either revise this issue by deleting your current comment, paste the template found [here](https://raw.githubusercontent.com/JosephLai241/URS/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md), then fill out all the fields, or close this issue and create a new one.

These are the instructions for creating a new bug report:

When you clicked "New Issue", you should have seen the options "Bug Report" and "Feature/Enhancement Request". Click the "Get started" button for the "Bug Report" and fill out all the fields within the pre-loaded template.

**Comment by JosephLai241** [comment]
Thank you for taking the time to fill out the bug template. Since you said you are new to programming, I did some reformatting based on the information you have included in your initial revision.

I believe this could be an issue that is unique to Windows. Unix-derived operating systems such as MacOS or Linux distributions use the forward slash, `/`, for its directory paths whereas Windows uses a backslash, `\`. 

The issue may lie in the current code for checking whether the scrape file you have passed into the analytical tools is valid. I will admit, that method needs a refactor and could be the reason why you are experiencing this problem. I develop on and use Arch Linux as my daily driver, so I have not run tests on a Windows machine.

I will have to do some more research before I make changes, but I will see about refactoring that method by using a cross-platform solution instead of one that assumes your machine is Unix-derived if that is indeed the issue, which seems likely. Your issue may be resolved once I merge the new pull request.

My schedule has been busy as of late, so I may not be able to look into this until sometime this weekend. Stay tuned for updates!

**Comment by lolfilmworks** [comment]
I appreciate your time and am sorry I did not fill out the bug form the first time, I figured it was a directory issue. Please do not stress yourself too much over it if there is anything I can do to be of service please let me know. Thanks for posting your awesome work online.

**Comment by JosephLai241** [comment]
No worries. I checked out your profile and it seems to me you created your account just to open this issue. I respect the effort you have already put in, and it's understandable that you were not aware of some unspoken GitHub "rules" without prior experience.

Thank you, I appreciate the feedback and I am glad you like this project (despite running into this bug)! All I would need from you is to test out the new changes once they are merged to the master branch and comment whether the changes fixed your issue. 🙂

**Comment by lolfilmworks** [comment]
Of course sir! I apologize, I saw the rules I broke afterwards and felt
pretty bad, I'm in my 30s so I'm used to a more "wild west" internet and am
just not starting to come to terms with the new order that more resembles
RL manners. Thank you again for all your hard work, reddit is a huge
compendium of knowledge and your project seems to be the tool I can find to
truly start to tap into it (and you do it free of cost, do you have a
donations program or link?).  I'll test the new build, and in the meantime
I am going to use it on my raspberry pi 4 to avoid the directory issue.
Thank you!

**Comment by JosephLai241** [comment]
No worries, I understand where you are coming from! I am just glad you found my program useful - it was initially created just for personal use until a friend suggested I upload it on GitHub. I never would have imagined this kind of growth and it is all thanks to you, a member of the open-source community.

I do have a [Patreon here](https://www.patreon.com/ursproject) if you would like to donate. You can also find it via the Sponsor button at the top of this repository. It is completely optional, but I would be very grateful if you decide to contribute! 😁

URS should work correctly on Raspbian/Raspberry Pi OS, so I believe you will be able to get the data you need when running it there. 👍

**Comment by lolfilmworks** [comment]
I sent you 10 on patreon, I don't have the money to do it monthly but I
wanted to give you something to show I was appreciative! :)

**Comment by JosephLai241** [comment]
Wow, thank you so much for the support! I will be sending you an email to the address associated with your Patreon account later today to follow up! 😄

**Comment by lolfilmworks** [comment]
no worries man, I'm not looking for results or anything I just appreciate
how kind/patient you were.

**Comment by lolfilmworks** [comment]
Thank you so much Joseph! I'll give it a shot later today.

**Comment by JosephLai241** [comment]
No problem! I believe the new release fixed the bug, so hopefully everything works fine now 👍🏻
