### ISSUE TITLE
Scrape all posts of a user/scrape only new posts

### ISSUE THREAD

**Issue by freshmre** [JosephLai241/URS#49]
I want to get all of a specific user's posts. What I'm doing now is `./Urs.py -u URS_test 9999`, but that's making redundant requests for controversial, hot, guilded and top; 403's if the number of posts is suffiently large and creates an output many times larger than it should be.
Is there a flag for new only like there is for subreddits? Or ideally a way to get all user history?

**Comment by JosephLai241** [comment]
Hi @freshmre, my deepest apologies for the extremely late response to your question. Unfortunately I have not implemented functionality to scrape individual Redditor attributes as mentioned at the bottom of [the Redditors section on the README](https://github.com/JosephLai241/URS#redditors), but I plan to introduce such functionality in a future iteration of URS.
